name: client-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸª Check out code
        uses: actions/checkout@v2
      - name: ğŸ‘Goto client and run tests
        run: cd client && npm i && npm test
